### PR TITLE
Add GetCachedTable function

### PR DESCRIPTION
**Pull request by bsoo**
Tableごとのputspoolを使い回すため、すでにキャッシュされているTableを取得する関数を追加しました。

### CODE REVIEW

**Comment by evalphobia** [comment]
@bsoo Thank you for the P-R.

Would you use this new method to get cached table in `GetTable` ?
https://github.com/evalphobia/aws-sdk-go-wrapper/blob/master/dynamodb/client.go#L103-L112

**Comment by bsoo** [comment]
> @bsoo Thank you for the P-R.
> 
> Would you use this new method to get cached table in `GetTable` ?
> https://github.com/evalphobia/aws-sdk-go-wrapper/blob/master/dynamodb/client.go#L103-L112

yes!

**Comment by bsoo** [comment]
> @bsoo Thank you for the P-R.
> 
> Would you use this new method to get cached table in `GetTable` ?
> https://github.com/evalphobia/aws-sdk-go-wrapper/blob/master/dynamodb/client.go#L103-L112

like this? 
https://github.com/evalphobia/aws-sdk-go-wrapper/pull/69/commits/268ba76f31ba7cbdda934e81877d83b27a2c2d89

**Comment by evalphobia** [comment]
Thanks! 🍡 

Note: https://github.com/evalphobia/aws-sdk-go-wrapper/releases/tag/v1.15.1

**Pull request merged**
