### PR TITLE
Make WaitTimeSeconds adjustable to support long polling

### PR DESCRIPTION
**Pull request by mgale**
I moved wait into a constant like expire and created a method to set the WaitTimeSeconds. I tested this locally using localstack and ran go test using the docker-compose setup.

### CODE REVIEW

**Comment by evalphobia** [comment]
@mgale Thank you for contributing!

Your suggestion looked good for me 👍 

To keep compatibility for the client who uses the old code, 
would you keep the code to use `wait = 1` when `num > 1`, something like below?


```go
func (q *Queue) Fetch(num int) ([]*Message, error) {
	wait := q.waitTimeSeconds

	if wait == 0 && num > 1 {
		wait = 1 // use long-polling for 1sec when to get multiple messages	
	}

...
	resp, err := q.service.client.ReceiveMessage(&SDK.ReceiveMessageInput{
		WaitTimeSeconds:     pointers.Long(wait),
```

**Comment by mgale** [comment]
I am going to cancel this PR for now. I will look into trying to support the above suggestion but more importantly I need to support FIFO queues which I think will require more work.

**Comment by evalphobia** [comment]
@mgale 
I think this PR for long polling will have benefits for other users.
If you reopen this, I'll merge this right away, then I'll add the codes for compatibility in another PR.

And after that, you'll add another PR for FIFO (maybe adding `MessageDeduplicationId` and `MessageGroupId` ?)

**Comment by mgale** [comment]
@evalphobia Sorry I didn't see your message until now. I have re-opened the PR however I have added more changes. 

I added a new delete method DeleteMessageWithReceipt and an AddMessageWithGroupID. I also added to the tests.

**Comment by mgale** [comment]
@evalphobia Do you want to coordinate this over email? gale.michael@gmail.com

**Comment by evalphobia** [comment]
@mgale Sorry for my late reply, (covid19 has changed our environment, but fortunately I'm healthy 👍)

Thank you for your commits!
Regarding go.mod, PR https://github.com/evalphobia/aws-sdk-go-wrapper/pull/56/ is faster and merged.
Would you remove it in this PR to solve conflict?

**Comment by mgale** [comment]
@evalphobia I have made the changes.

**Comment by evalphobia** [comment]
Thanks! :octocat: 

Note: https://github.com/evalphobia/aws-sdk-go-wrapper/releases/tag/v1.13.2

**Pull request merged**
