### PR TITLE
Add s3 prefix opt

### PR DESCRIPTION
**Pull request by gotokatsuya**
## Fix

Add prefix option to AmazonS3.GetBucket's arg

:+1:

### CODE REVIEW

**Comment by gotokatsuya** [comment]
@evalphobia  

Review, please

**Comment by evalphobia** [comment]
@gotokatsuya  Thanks!

I think the signature is a bit weird, passing bucket name and prefix at the same time.
prefix should be automatically added to the bucket name in this context.

How about to set prefix field in `AmazonS3` struct?

```go
type AmazonS3 struct {
    buckets map[string]*Bucket
    client  *SDK.S3
    prefix string
}

func (s *AmazonS3) SetPrefix(prefix string){
    s.prefix = prefix
}
```

**Comment by gotokatsuya** [comment]
@evalphobia 

Looks good. 

I rewrote.

```go
// Create new AmazonS3 struct
func newClient(conf auth.Config) *AmazonS3 {
	s := &AmazonS3{}
	s.buckets = make(map[string]*Bucket)

	conf.SetDefault(defaultRegion, defaultEndpoint)
	awsConf := conf.Config
	if *awsConf.Endpoint != "" {
		awsConf.S3ForcePathStyle = Bool(true)
	}
	s.client = SDK.New(awsConf)
	s.prefix = config.GetConfigValue(s3ConfigSectionName, "prefix", defaultBucketPrefix)
	return s
}

func (s *AmazonS3) SetPrefix(prefix string){
    s.prefix = prefix
}

// get bucket
func (s *AmazonS3) GetBucket(bucket string) *Bucket {
	bucketName := s.prefix + bucket

	// get the bucket from cache
	b, ok := s.buckets[bucketName]
	if ok {
		return b
	}

	b = &Bucket{}
	b.client = s.client
	b.name = bucketName
	s.buckets[bucketName] = b
	return b
}
```

Right ?

**Comment by gotokatsuya** [comment]
And I prefer ```bucketPrefix``` .
```
// set bucket prefix
func (s *AmazonS3) SetBucketPrefix(bucketPrefix string) {
	s.bucketPrefix = bucketPrefix
}
```

**Comment by evalphobia** [comment]
@gotokatsuya  looks good.

**Comment by gotokatsuya** [comment]
@evalphobia Thank you so much! DONE !

**Pull request merged**
